trigger:
  branches:
    include:
      - boost

variables:
  CONAN_BUILD_TYPES: Release
  CONAN_ARCHS: x86_64
  CONAN_USERNAME: bincrafters
  CONAN_CHANNEL: testing
  CONAN_UPLOAD_DEPENDENCIES: all
  CONAN_BUILD_POLICY: missing
  CONAN_REMOTES: https://api.bintray.com/conan/bincrafters/public-conan@bincrafters
  BOOST_VERSION: 1.71.0
  BOOST_BASE_VERSION: 2.1.0

stages:
- stage: Build
  jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        Clang 9:
          CONAN_DOCKER_IMAGE: conanio/clang9
          CONAN_CLANG_VERSIONS: 9
        GCC 9:
          CONAN_DOCKER_IMAGE: conanio/gcc9
          CONAN_CLANG_VERSIONS: 9
    steps:
    - bash: |
        set -e
        uname -a
        sudo apt-get update
        sudo apt-get install software-properties-common apt-file
      displayName: 'Install: APT'
    - bash: |
        set -e
        uname -a
        sudo apt-add-repository -y "ppa:deadsnakes/ppa"
        sudo apt-get update
        sudo apt-get install python3.7
        sudo apt-get install python3.7-dev
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3 get-pip.py
      displayName: 'Install: Python'
    - bash: |
        set -e
        pip3 install --upgrade pip
        pip3 install --upgrade conan
        pip3 install --upgrade conan_package_tools
        pip3 install --upgrade https://github.com/grafikrobot/boost_lib_stats/archive/master.zip
      displayName: 'Install: PIP'
    - bash: |
        set -e
        python3 ./recipes/boost_base/all/src/script/build_all.py ++version=${BOOST_VERSION} ++base-version=${BOOST_BASE_VERSION}
      displayName: 'Build'
  - job: 'macOS'
    strategy:
      matrix:
        Xcode 11.2:
          CONAN_APPLE_CLANG_VERSIONS: 11.0
          XCODE_APP: /Applications/Xcode_11.2.app
          VM_IMAGE: 'macOS-10.14'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - bash: |
        set -e
        uname -a
        sudo xcode-select -switch ${XCODE_APP}
        which clang++
      displayName: Install
    - bash: |
        set -e
        brew update
        brew reinstall python3
      displayName: 'Install: Python'
    - bash: |
        set -e
        pip3 install --upgrade pip
        pip3 install --upgrade conan
        pip3 install --upgrade conan_package_tools
        pip3 install --upgrade https://github.com/grafikrobot/boost_lib_stats/archive/master.zip
      displayName: 'Install: PIP'
    - bash: |
        set -e
        python3 ./recipes/boost_base/all/src/script/build_all.py ++version=${BOOST_VERSION} ++base-version=${BOOST_BASE_VERSION}
      displayName: 'Build'
  - job: 'Windows'
    strategy:
      matrix:
        VS 2019:
          CONAN_VISUAL_VERSIONS: 16
          CONAN_VISUAL_RUNTIMES: MT
          VM_IMAGE: 'windows-2019'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x' 
        addToPath: true 
        architecture: 'x64'
      name: Python3
      displayName: 'Install: Python'
    - powershell: |
        python -m pip install --upgrade pip
        pip install --upgrade conan
        pip install --upgrade conan_package_tools
        pip install --upgrade "https://github.com/grafikrobot/boost_lib_stats/archive/master.zip"
      displayName: 'Install: PIP'
    - powershell: |
        python ./recipes/boost_base/all/src/script/build_all.py ++version=$env:BOOST_VERSION ++base-version=$env:BOOST_BASE_VERSION
      displayName: 'Build'
