name: "Package: Bug Report"
description: "Report a bug, something does not work as it supposed to"
title: "[package] LIBRARY-NAME/LIBRARY-VERSION: SHORT DESCRIPTION"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
          Please don't forget to update the issue title.
          Include all applicable information to help us reproduce your problem.
  - type: markdown
    attributes:
      value: "### Package and Environment Details (include every applicable attribute)"
  - type: input
    id: os
    attributes:
      label: Operating System + Version
      placeholder: Linux Ubuntu 16.04
    validations:
      required: false
  - type: input
    id: compiler
    attributes:
      label: Compiler + Version
      placeholder: GCC 10
    validations:
      required: false
  - type: input
    id: docker
    attributes:
      label: Docker Image (if used)
      placeholder: conanio/gcc10-ubuntu16.04
    validations:
      required: false
  - type: input
    id: conan
    attributes:
      label: Conan Version
      placeholder: 1.41.0
    validations:
      required: false
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: 3.10.0
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
          ### Package and Environment Details (include every applicable attribute
  - type: textarea
    id: what-happened
    attributes:
      label: "### Conan profile"
      description: output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use
      placeholder: Put your profile output here
    validations:
      required: true
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
